services:
  nuxt-ssg:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nuxt-ssg-container
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NODE_ENV=production
    restart: always
