services:
  nuxt-ssg:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nuxt-ssg-container
    ports:
      - "185.185.71.140:80:80"
      - "185.185.71.140:443:443"
    environment:
      - NODE_ENV=production
    restart: always
