services:
  nuxt-ssg:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nuxt-ssg-container
    ports:
      - "443:443"
    volumes:
      - ./.nginx:/etc/nginx
    environment:
      - NODE_ENV=production
    restart: always
