services:
  nuxt-ssg:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nuxt-ssg-container
    ports:
      - "80:80"
    volumes:
      - ./.nginx:/etc/nginx
      - ./.letsencrypt:/usr/share/nginx/html
    environment:
      - NODE_ENV=production
    restart: always
