services:
  nuxt-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      NODE_OPTIONS: --max_old_space_size=4096
    deploy:
      resources:
        limits:
          memory: 4G
    expose:
      - "3000"
    restart: unless-stopped
    networks:
      - nuxt-network

  # Nginx (прокси к Nuxt)
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public/favicon.svg:/usr/share/nginx/html/assets/favicon.svg
      - ./public/touch-icon.png:/usr/share/nginx/html/assets/touch-icon.png
      - ./.nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./.nginx/mime.types:/etc/nginx/conf/mime.types
      - ./.nginx/certs/certificate.crt:/etc/nginx/ssl/certificate.crt
      - ./.nginx/certs/certificate.key:/etc/nginx/ssl/certificate.key
    depends_on:
      - nuxt-app
    restart: unless-stopped
    networks:
      - nuxt-network

networks:
  nuxt-network:
    driver: bridge