import {
  DISCLAIMER_ROUTE,
  HISTORY_ROUTE,
  HOME_ROUTE,
  HOW_TO_DEFINE_ROUTE,
  PEOPLE_ROUTE,
  PROFILE_ROUTE,
  SPECIALISTS_ROUTE,
  TEAMS_ROUTE,
  TESTS_ROUTE,
  WHAT_IS_IT_ROUTE,
  THEORY_ROUTE,
} from "./staticRoutes";
import {
  SOCIOTYPE_CARD_ROUTE,
  SOCIOTYPE_TAB_ROUTE,
  SOCIOTYPE_KIDS_CARD_ROUTE,
  KIDS_ROUTE,
} from "./sociotypes";

const ROUTES = [
  HOME_ROUTE,
  SOCIOTYPE_CARD_ROUTE,
  SOCIOTYPE_TAB_ROUTE,
  SOCIOTYPE_KIDS_CARD_ROUTE,
  WHAT_IS_IT_ROUTE,
  THEORY_ROUTE,
  DISCLAIMER_ROUTE,
  HOW_TO_DEFINE_ROUTE,
  TESTS_ROUTE,
  PROFILE_ROUTE,
  PEOPLE_ROUTE,
  SPECIALISTS_ROUTE,
  TEAMS_ROUTE,
  KIDS_ROUTE,
  HISTORY_ROUTE,
] as const;

export default ROUTES;
