import type { SociotypeDataType } from "@types";

const ESTJ: SociotypeDataType = {
  id: "ESTJ",
  quadra: "earth",
  role: "king",
  alias: "Штирлиц",
  mindKey: "rational-4",
  mindset: "algorithmic",
  name: "Администратор",
  typeName: "administrator",
  gender: "male",
  club: "pragmatist",
  tarot: "pentacles",
  psychotype: "caring",
  populationPercentage: "8 ~ 12%",
  aspects: {
    lives: "business",
    creates: "comfort",
    mad: "logic",
    does: "will",
    afraid: "emotions",
    suffers: "time",
    desires: "people",
    likes: "ideas",
  },
  stimulant: "status",
  communication: "business",
  companion: "stubborn",
  temperament: "choleric",
  alignment: "lawfulEvil",
  yungs: ["rational", "sensory", "logic", "extravert"],
  reinin: [
    "dynamic",
    "negativist",
    "questim",
    "tactician",
    "emotivist",

    "process",
    "compliant",
    "provident",

    "reasonable",
    "objective",
    "aristocrat",
  ],
  intertypeRelations: {
    dual: "INFJ",
    activity: "ENFP",
    mirror: "ISTP",
    identical: "ESTJ",
    kindred: "ENTJ",
    semidual: "ISFJ",
    pragmatic: "ESFJ",
    illusionary: "INTJ",
    beneficiary: "ISFP",
    giver: "ESFP",
    supervisor: "ENTP",
    underling: "INTP",
    quasidentical: "ESTP",
    parallel: "INFP",
    contrary: "ISTJ",
    superego: "ENFJ",
  },
  socionicAbbrevation: "ЛСЭ",
  personalitiesTerm: "Executive",
  shortDesctiption: {
    personAttributes: "Практичный, реалистичный, конкретный.",
    personDesctiption: [
      "Решителен, быстро переходит к реализации решений. Организовывает проекты и людей для выполнения задач, концентрируется на достижении результатов наиболее эффективным способом.",
      "Заботится о рутинных деталях. Имеет четкий набор логических стандартов, систематически следует им и хочет, чтобы другие также следовали им. Настойчив в реализации своих планов.",
    ],
  },
};

export default ESTJ;
