import type { ReininSign } from "@types";

export const REININ_SIGNS: Record<ReininSign, string> = {
  static: "Статик",
  dynamic: "Динамик",
  positivist: "Позитивист",
  negativist: "Негативист",
  questim: "Квестим",
  declatim: "Деклатим",
  tactician: "Тактик",
  strategist: "Стратег",
  constructivist: "Конструктивист",
  emotivist: "Эмотивист",
  process: "Процесс",
  result: "Результат",
  compliant: "Уступчивый",
  stubborn: "Упрямый",
  careless: "Беспечный",
  provident: "Предусмотрительный",
  reasonable: "Рассудительный",
  decisive: "Решительный",
  subjective: "Субъективный",
  objective: "Объективный",
  democrat: "Демократ",
  aristocrat: "Аристократ",
};
