import type { FamousPersonType } from "@types";
import { GenderEnum } from "@shared/constants";

const FAMOUS_PEOPLE: Array<FamousPersonType> = [
  {
    id: "ENTP",
    name: "Мила Йовович",
    role: "Актриса",
    birthDate: "17.12.1975",
    zodiac: "sagittarius",
    bazi: "rat",
    photo: "public/images/people/mila.jpg",
    gender: GenderEnum.female,
  },
  {
    id: "ENTP",
    name: "Билли Айлиш",
    role: "Певица",
    birthDate: "18.12.2001",
    zodiac: "sagittarius",
    bazi: "rat",
    photo: "public/images/people/billi.jpg",
    gender: GenderEnum.female,
  },
  {
    id: "ENTP",
    name: "Стив Джобс",
    role: "Предприниматель",
    birthDate: "24.02.1955",
    zodiac: "aries",
    bazi: "goat",
    photo: "public/images/people/steve.jpg",
    gender: GenderEnum.male,
  },
  {
    id: "ENTP",
    name: "Роберт Дауни Младший",
    role: "Актер",
    birthDate: "04.04.1965",
    zodiac: "aries",
    bazi: "snake",
    photo: "public/images/people/robert.jpg",
    gender: GenderEnum.male,
  },
  {
    id: "ENTP",
    name: "Генри Кэвилл",
    role: "Актер",
    birthDate: "05.05.1983",
    zodiac: "aries",
    bazi: "pig",
    photo: "public/images/people/henry.jpg",
    gender: GenderEnum.male,
  },
  {
    id: "ENTP",
    name: "Аушра Аугустинавичюте",
    birthDate: "04.04.1927",
    gender: GenderEnum.female,
    role: "Психолог, автор",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
  {
    id: "ENTJ",
    name: "Илон Маск",
    birthDate: "28.06.1971",
    gender: GenderEnum.male,
    role: "Бизнесмен",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
  {
    id: "ENTP",
    name: "Данила Поперечный",
    birthDate: "10.03.1994",
    gender: GenderEnum.male,
    role: "Стендап-комик",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
  {
    id: "ISFP",
    name: "Брэд Питт",
    birthDate: "18.12.1963",
    gender: GenderEnum.male,
    role: "Актер",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
  {
    id: "ENTP",
    name: "Ричард Бренсон",
    birthDate: "18.07.1950",
    gender: GenderEnum.male,
    role: "Бизнесмен",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
  {
    id: "ISFJ",
    name: "Александр Пушной",
    birthDate: "16.05.1975",
    gender: GenderEnum.male,
    role: "Телеведущий",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
  {
    id: "ENTP",
    name: "Киану Ривз",
    birthDate: "02.09.1964",
    gender: GenderEnum.male,
    role: "Актер",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
  {
    id: "ENTP",
    name: "Феликс Чельберг",
    birthDate: "24.10.1989",
    gender: GenderEnum.male,
    role: "Видеоблогер Pewdiepie",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
  {
    id: "ESFP",
    name: "Дмитрий Нагиев",
    birthDate: "04.04.1967",
    gender: GenderEnum.male,
    role: "Актер",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
  {
    id: "ENTJ",
    name: "Владимир Путин",
    birthDate: "07.10.1952",
    gender: GenderEnum.male,
    role: "Президент РФ",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
  {
    id: "ESTJ",
    name: "Арнольд Шварцнеггер",
    birthDate: "30.07.1947",
    gender: GenderEnum.male,
    role: "Актер",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
  {
    id: "ENTP",
    name: "Евгений Чичваркин",
    birthDate: "10.09.1974",
    gender: GenderEnum.male,
    role: "Бизнесмен",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
  {
    id: "INTP",
    name: "Альберт Эйнштейн",
    birthDate: "14.03.1955",
    gender: GenderEnum.male,
    role: "Ученый",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
  {
    id: "ENTP",
    name: "Стив Джобс",
    birthDate: "24.02.1955",
    gender: GenderEnum.male,
    role: "Бизнесмен",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
  {
    id: "ISTP",
    name: "Стив Возняк",
    birthDate: "11.08.1950",
    gender: GenderEnum.male,
    role: "Бизнесмен",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
  {
    id: "INFJ",
    name: "Дада Садананда",
    birthDate: "undefined..undefined",
    gender: GenderEnum.male,
    role: "Медитативный йогин",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
  {
    id: "ENTP",
    name: "Мила Йовович",
    birthDate: "17.12.1975",
    gender: GenderEnum.female,
    role: "Актриса",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
  {
    id: "ISTJ",
    name: "Натали Портман",
    birthDate: "09.06.1981",
    gender: GenderEnum.female,
    role: "Актриса",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
  {
    id: "INFJ",
    name: "Барак Обама",
    birthDate: "04.08.1961",
    gender: GenderEnum.male,
    role: "Бывший президент США",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
  {
    id: "ISTP",
    name: "Сильвестр Сталоне",
    birthDate: "06.07.1946",
    gender: GenderEnum.male,
    role: "Актер",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
  {
    id: "ESFJ",
    name: "Том Харди",
    birthDate: "15.09.1977",
    gender: GenderEnum.male,
    role: "Актер",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
  {
    id: "ENTP",
    name: "Григорий Перельман",
    birthDate: "13.06.1966",
    gender: GenderEnum.male,
    role: "Математик",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
  {
    id: "ENTJ",
    name: "Павел Дуров",
    birthDate: "10.10.1984",
    gender: GenderEnum.male,
    role: "Бизнесмен",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
  {
    id: "ESFJ",
    name: "Эдуард Хиль",
    birthDate: "04.09.1934",
    gender: GenderEnum.male,
    role: "Певец СССР",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
  {
    id: "ENFJ",
    name: "Виктор Сухоруков",
    birthDate: "10.11.1951",
    gender: GenderEnum.male,
    role: "Актер",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
  {
    id: "ENTJ",
    name: "Олег Тиньков",
    birthDate: "25.12.1967",
    gender: GenderEnum.male,
    role: "Предприниматель",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
  {
    id: "ENTP",
    name: "Александр Гордон",
    birthDate: "20.02.1964",
    gender: GenderEnum.male,
    role: "Телеведущий",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
  {
    id: "INTJ",
    name: "Ирина Хакамада",
    birthDate: "13.05.1955",
    gender: GenderEnum.female,
    role: "Медиаперсона",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
  {
    id: "ESTJ",
    name: "Брайан Крэнстон",
    birthDate: "07.03.1956",
    gender: GenderEnum.male,
    role: "Актер",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
  {
    id: "ESTJ",
    name: "Анжелина Джоли",
    birthDate: "04.06.1975",
    gender: GenderEnum.female,
    role: "Актриса",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
  {
    id: "INFP",
    name: "Иван Охлобыстин",
    birthDate: "22.07.1966",
    gender: GenderEnum.male,
    role: "Актер",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
  {
    id: "ISFJ",
    name: "Дмитрий Медведев",
    birthDate: "14.09.1965",
    gender: GenderEnum.male,
    role: "Бывший президент РФ",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
  {
    id: "ESTJ",
    name: "Алексей Навальный",
    birthDate: "04.06.1976",
    gender: GenderEnum.male,
    role: "Политик",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
  {
    id: "ISTJ",
    name: "Кира Найтли",
    birthDate: "26.03.1985",
    gender: GenderEnum.female,
    role: "Актриса",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
  {
    id: "INTJ",
    name: "Киллиан Мерфи",
    birthDate: "25.05.1976",
    gender: GenderEnum.male,
    role: "Актер",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
  {
    id: "ESTJ",
    name: "Дуэйн Джонсон",
    birthDate: "02.05.1972",
    gender: GenderEnum.male,
    role: "Актер",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
  {
    id: "ESTJ",
    name: "Денис Семинихин",
    birthDate: "03.07.1971",
    gender: GenderEnum.male,
    role: "Видеоблогер",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
  {
    id: "INFP",
    name: "Илья Прусикин",
    birthDate: "08.04.1985",
    gender: GenderEnum.male,
    role: "Певец",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
  {
    id: "INFP",
    name: "Юрий Николаенко",
    birthDate: "17.05.1989",
    gender: GenderEnum.male,
    role: "Актер",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
  {
    id: "ESTJ",
    name: "Ума Турман",
    birthDate: "29.05.1970",
    gender: GenderEnum.female,
    role: "Актриса",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
  {
    id: "ESTJ",
    name: "Бен Аффлек",
    birthDate: "15.08.1972",
    gender: GenderEnum.male,
    role: "Актер",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
  {
    id: "ENTJ",
    name: "Мэтт Дэймон",
    birthDate: "08.10.1970",
    gender: GenderEnum.male,
    role: "Актер",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
  {
    id: "ESTJ",
    name: "Борис Ельцин",
    birthDate: "01.02.1931",
    gender: GenderEnum.male,
    role: "Бывший президент РФ",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
  {
    id: "ISFP",
    name: "Том Круз",
    birthDate: "03.07.1962",
    gender: GenderEnum.male,
    role: "Актер",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
  {
    id: "ESTJ",
    name: "Николь Кидман",
    birthDate: "20.06.1967",
    gender: GenderEnum.female,
    role: "Актриса",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
  {
    id: "ISFP",
    name: "Хавьер Бардем",
    birthDate: "01.03.1969",
    gender: GenderEnum.male,
    role: "Актер",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
  {
    id: "ENFJ",
    name: "Максим Аверин",
    birthDate: "26.11.1975",
    gender: GenderEnum.male,
    role: "Актер",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
  {
    id: "ISTP",
    name: "Гейб Ньюэлл",
    birthDate: "03.11.1962",
    gender: GenderEnum.male,
    role: "Бизнесмен",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
  {
    id: "ISTP",
    name: "Джон Леннон",
    birthDate: "08.12.1980",
    gender: GenderEnum.male,
    role: "Музыкант",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
  {
    id: "ESFP",
    name: "Йоко Оно",
    birthDate: "18.02.1933",
    gender: GenderEnum.female,
    role: "Художник",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
  {
    id: "ENFJ",
    name: "Илья Глинников",
    birthDate: "19.09.1984",
    gender: GenderEnum.male,
    role: "Актер",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
  {
    id: "ISTJ",
    name: "Галь Гадот",
    birthDate: "30.04.1985",
    gender: GenderEnum.female,
    role: "Актриса",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
  {
    id: "ENTJ",
    name: "Карл Юнг",
    birthDate: "26.07.1875",
    gender: GenderEnum.male,
    role: "Психоаналитик",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
  {
    id: "ESTJ",
    name: "Зигмунд Фрейд",
    birthDate: "23.09.1856",
    gender: GenderEnum.male,
    role: "Психоаналитик",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
  {
    id: "ISFJ",
    name: "Моника Белуччи",
    birthDate: "23.09.1856",
    gender: GenderEnum.male,
    role: "Актриса",
    zodiac: "aries",
    bazi: "pig",
    photo: "",
  },
] as const;

export default FAMOUS_PEOPLE;
